<?php

namespace Database\Seeders;

use App\Models\Acara;
use App\Models\Tamu;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

/**
 * Daftar tamu Anugerah TIMES Indonesia 2025, disalin dari basis data produksi
 * (dump 16 September 2026, 98 baris).
 *
 * Id dipertahankan apa adanya: berkas QR bernama qrcodes/{id}.png dan tautan
 * undangan /undangan/{id}/{nama} sudah beredar ke tamu. updateOrCreate membuat
 * seeder ini aman dijalankan berulang.
 */
class TamuSeeder extends Seeder
{
    public function run(): void
    {
        $acara = Acara::whereYear('mulai', 2025)->first() ?? Acara::create([
            'nama' => 'Anugerah TIMES Indonesia',
            'mulai' => Carbon::parse('2025-11-27 18:00:00', Acara::ZONA),
            'selesai' => Carbon::parse('2025-11-27 21:00:00', Acara::ZONA),
            'tempat' => 'Grand Ballroom',
            'alamat' => 'Grand Mercure Malang Mirama, Jl. Raden Panji Suroso No.7, Purwodadi, Kec. Blimbing, Kota Malang, Jawa Timur 65126',
            'aktif' => false,
        ]);

        foreach (self::TAMU as $tamu) {
            Tamu::updateOrCreate(
                ['id' => $tamu['id']],
                $tamu + ['acara_id' => $acara->id]
            );
        }
    }

    private const TAMU = [
        ['id' => 1, 'code' => 'Z42LHD9W', 'nama' => 'dr. Ayu Widyaningrum, MM, Master of AAAM, Master of IBAMS', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 4, 'qr_code' => 'qrcodes/1.png', 'pic' => 'Dhina', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:24:07'],
        ['id' => 2, 'code' => 'JGA3OFUG', 'nama' => 'dr. Karolin Margret Natasa, M.H', 'lembaga' => 'Bupati Kabupaten Landak', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/2.png', 'pic' => 'Hainor', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:43:22'],
        ['id' => 3, 'code' => 'TVHEDWF1', 'nama' => 'Drs. Cornelis, M.H', 'lembaga' => 'Anggota DPR RI', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/3.png', 'pic' => 'Hainor', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:43:08'],
        ['id' => 4, 'code' => 'BQZAVNJ7', 'nama' => 'dr. Rully Suwartiningsih, S.Ked., MM.', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 2, 'qr_code' => 'qrcodes/4.png', 'pic' => 'Hainor', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:49:15'],
        ['id' => 5, 'code' => 'KTPZZ5RZ', 'nama' => 'Kombes Pol Nanang Haryono SH, SIK, MSi', 'lembaga' => 'Kapolresta Malang Kota', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/5.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 19:30:50'],
        ['id' => 6, 'code' => '6RAQGRYJ', 'nama' => 'Dr. Yayan Riyanto, S.H., M.H', 'lembaga' => '', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/6.png', 'pic' => 'Yono', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:30:15'],
        ['id' => 7, 'code' => 'OHJL4YNB', 'nama' => 'Dr. dr. Ariani, M.Kes, Sp.A, SubSp., TKPS(K)', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 2, 'qr_code' => 'qrcodes/7.png', 'pic' => 'Yuli', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:25:58'],
        ['id' => 8, 'code' => 'RI6OVD6Q', 'nama' => 'Direktur Utama', 'lembaga' => 'PT Brawijaya Multi Usaha', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/8.png', 'pic' => 'Naning', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:52:13'],
        ['id' => 9, 'code' => '87APZB48', 'nama' => 'M. Rusdi Sutejo\n', 'lembaga' => 'Bupati Pasuruan', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/9.png', 'pic' => 'Munir', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:11:14'],
        ['id' => 10, 'code' => 'BEBXY8YM', 'nama' => 'Baznas Kota Malang', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/10.png', 'pic' => 'Siti', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:56:44'],
        ['id' => 11, 'code' => 'LDGHBBYC', 'nama' => 'Ali Muthohirin', 'lembaga' => 'Wakil Wali Kota Malang', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/11.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 20:12:15'],
        ['id' => 12, 'code' => '1ZSRPRR6', 'nama' => 'Dr. Ir. H. Wahyu Hidayat, M.M', 'lembaga' => 'Wali Kota Malang', 'alamat' => null, 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/12.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 20:06:00'],
        ['id' => 13, 'code' => 'QYTCLAZ6', 'nama' => 'Prof. Dr. Hj. Ilfi Nur Diana, M.Si', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/13.png', 'pic' => 'Yuli', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 19:31:51'],
        ['id' => 14, 'code' => 'HTNSW2RM', 'nama' => 'Ahmad Dzulfikar Nurrahman', 'lembaga' => 'Kepala DLH Kabupaten Malang', 'alamat' => null, 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 2, 'qr_code' => 'qrcodes/14.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 19:46:13'],
        ['id' => 15, 'code' => 'N95JEXPY', 'nama' => 'Cempaka Foundation', 'lembaga' => '', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/15.png', 'pic' => 'Munir', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 19:31:32'],
        ['id' => 16, 'code' => 'J87MPV7I', 'nama' => 'Bahlil Laladalia', 'lembaga' => '', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/16.png', 'pic' => 'Ainun', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:11'],
        ['id' => 17, 'code' => '42H7KM33', 'nama' => 'Drs. H. Eman Suherman, M.M', 'lembaga' => 'Bupati Majalengka', 'alamat' => null, 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/17.png', 'pic' => 'Bambang', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:51:54'],
        ['id' => 18, 'code' => 'WJLIWYFX', 'nama' => 'Yusuf Rio Wahyu Prayogo', 'lembaga' => 'Bupati Situbondo', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/18.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 19:44:54'],
        ['id' => 19, 'code' => 'W45QNWHC', 'nama' => 'dr. Mohammad Haris', 'lembaga' => 'Bupati Probolinggo', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/19.png', 'pic' => 'Anwar', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 20:14:25'],
        ['id' => 20, 'code' => 'SJMHTKP0', 'nama' => 'Suryadi, S.Pd., M.M', 'lembaga' => 'Angggota DPRD Kota Malang', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/20.png', 'pic' => 'Ainun', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:12'],
        ['id' => 21, 'code' => 'TIXFNZJ0', 'nama' => 'Muchlis, S.Pd', 'lembaga' => 'Anggota DPRD Kab Probolinggo', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/21.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 19:20:29'],
        ['id' => 22, 'code' => 'ZVXZ7F3O', 'nama' => 'Putri Aidillah Nurfitriyah Kriswanto', 'lembaga' => 'Anggota DPRD Kota Malang', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/22.png', 'pic' => 'Hainor', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:12'],
        ['id' => 23, 'code' => 'DBKFURH2', 'nama' => 'KRA. Dwi Indrotito Cahyono, S.H., M.M', 'lembaga' => '', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/23.png', 'pic' => 'Yono', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 19:36:13'],
        ['id' => 24, 'code' => 'JSH46G6H', 'nama' => 'Dr. Laily Abida, S.Psi, M.Psi', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/24.png', 'pic' => 'Siti', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:47:56'],
        ['id' => 25, 'code' => 'FMUIUQQR', 'nama' => 'Pimpinan Varnion', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 2, 'qr_code' => 'qrcodes/25.png', 'pic' => 'Ferry', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:50:22'],
        ['id' => 26, 'code' => '53XBAUTP', 'nama' => 'Sugeng Widodo', 'lembaga' => '', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/26.png', 'pic' => '', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:08:16'],
        ['id' => 27, 'code' => 'RSFUBYBO', 'nama' => 'Taufiq Saguanto', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 2, 'qr_code' => 'qrcodes/27.png', 'pic' => null, 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:38:15'],
        ['id' => 28, 'code' => 'DT53NG8V', 'nama' => 'Muhammad Ali Mahfud', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 2, 'qr_code' => 'qrcodes/28.png', 'pic' => 'Fani', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:07:47'],
        ['id' => 29, 'code' => 'SE7ZXBXV', 'nama' => 'Panetep Bagus Samudro', 'lembaga' => '', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/29.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:59:47'],
        ['id' => 30, 'code' => 'SHSZFUDA', 'nama' => 'Abdul Kodir', 'lembaga' => '', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/30.png', 'pic' => 'Hainor', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:52:33'],
        ['id' => 31, 'code' => 'FFJWO7NT', 'nama' => 'Kampung Coklat', 'lembaga' => '', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/31.png', 'pic' => '', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:12'],
        ['id' => 33, 'code' => 'N4CZQTTZ', 'nama' => 'Pimpinan Mister Pia', 'lembaga' => '', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/33.png', 'pic' => 'Wawa', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:31:29'],
        ['id' => 34, 'code' => 'X3LZP86Q', 'nama' => 'Pimpinan Buah Tangan', 'lembaga' => '', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/34.png', 'pic' => 'Wawa', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:12'],
        ['id' => 35, 'code' => '2LFU3GLV', 'nama' => 'Pimpinan Kopi Berdikari', 'lembaga' => '', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/35.png', 'pic' => 'Yono', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:08:45'],
        ['id' => 36, 'code' => 'T4GQHIBM', 'nama' => 'Pimpinan Alamo', 'lembaga' => '', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/36.png', 'pic' => 'Wawa', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:13'],
        ['id' => 39, 'code' => 'VZ91BSIZ', 'nama' => 'Prof. Widodo, S.Si., M.Si., Ph.D.Med.Sc', 'lembaga' => 'Rektor Universitas Brawijaya', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/39.png', 'pic' => 'Fiki', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:13'],
        ['id' => 40, 'code' => 'MP2OSIWO', 'nama' => 'Prof. Dr. Hariyono, M.Pd.', 'lembaga' => 'Rektor Universitas Negeri Malang', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/40.png', 'pic' => 'Fiki', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:13'],
        ['id' => 41, 'code' => 'TDHETABZ', 'nama' => 'Prof. Drs. H. Junaidi, M.Pd., Ph.D', 'lembaga' => 'Rektor Universitas Islam Malang', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/41.png', 'pic' => 'Fiki', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:13'],
        ['id' => 42, 'code' => 'Q5RMUQ2Z', 'nama' => 'Dr. Ir. Setya Budhi Udrayana, S.Pt, M.Si, IPM', 'lembaga' => 'Direktur Politeknik Pembangunan Pertanian Malang', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/42.png', 'pic' => 'Ferry', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:55:03'],
        ['id' => 43, 'code' => 'UVT3HQGN', 'nama' => 'Supriatna Adhisuwignjo, S.T., M.T', 'lembaga' => 'Direktur Politeknik Negeri Malang', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/43.png', 'pic' => 'Fiki', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:13'],
        ['id' => 44, 'code' => 'R1JFNQ2F', 'nama' => 'Dr. Anwar, S.H., M.Hum', 'lembaga' => 'Rektor Universitas Widyagama', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/44.png', 'pic' => 'Fiki', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:13'],
        ['id' => 45, 'code' => 'OZXU6S2J', 'nama' => 'KH. Imron Rosyadi Hamid, SE, MSi, PhD', 'lembaga' => 'Rektor UNIRA Malang', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/45.png', 'pic' => 'Fiki', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:13'],
        ['id' => 46, 'code' => 'L8XNXKBO', 'nama' => 'Dr. Evy Poerbaningtyas, S.Si, M.T.', 'lembaga' => 'Rektor Ubhinus (STIKI)', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/46.png', 'pic' => 'Fiki', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:13'],
        ['id' => 47, 'code' => 'U7KAOLGC', 'nama' => 'Dr. Klemens Mere, S.E., M.Pd., M.M., M.H., M.A.P., M.Ak', 'lembaga' => 'Rektor Universitas Katolik Widya Karya', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/47.png', 'pic' => 'Fiki', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:13'],
        ['id' => 48, 'code' => 'CON2A81U', 'nama' => 'Shalimar Hotel', 'lembaga' => '', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/48.png', 'pic' => 'Wawa', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:59:58'],
        ['id' => 49, 'code' => 'YJDPXPJS', 'nama' => 'Tugu Hotel', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/49.png', 'pic' => 'Yuli', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 18:41:59'],
        ['id' => 50, 'code' => '5P9NOQMU', 'nama' => 'Grand Mercure Malang Mirama', 'lembaga' => '', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/50.png', 'pic' => 'Wawa', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 19:18:59'],
        ['id' => 51, 'code' => 'HR5R66PE', 'nama' => 'Ir. R. Agoes Soeryanto', 'lembaga' => 'Ketua PD XIII GM FKPPI Jatim', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/51.png', 'pic' => 'Ainun', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:13'],
        ['id' => 52, 'code' => 'INCCX9HU', 'nama' => '⁠KH Israqunnajah', 'lembaga' => 'Ketua PCNU Kota Malang', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/52.png', 'pic' => 'Ainun', 'status' => 'belum', 'created_at' => null, 'updated_at' => '2025-11-21 09:13:13'],
        ['id' => 53, 'code' => 'T2EO7DPI', 'nama' => 'Dwi Eko Lokononto', 'lembaga' => 'Pemred Beritajatim', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/53.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 19:05:40'],
        ['id' => 54, 'code' => 'UZOE2648', 'nama' => 'Saptini Darmaningrum', 'lembaga' => 'Pengurus AMSI Nasional', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/54.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 19:04:45'],
        ['id' => 55, 'code' => 'J5GAN89P', 'nama' => 'Yulian Agung Effrata', 'lembaga' => 'Ketua NPCI Kab Malang', 'alamat' => '', 'is_register' => null, 'telepon' => '', 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/55.png', 'pic' => 'Fani', 'status' => 'datang', 'created_at' => null, 'updated_at' => '2025-11-27 19:22:01'],
        ['id' => 81, 'code' => 'L5FRE1XS', 'nama' => 'Dr. Ir. H. Wahyu Hidayat, M.M', 'lembaga' => 'Wali Kota Malang', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/81.png', 'pic' => 'Ainun', 'status' => 'belum', 'created_at' => '2025-11-22 10:11:02', 'updated_at' => '2025-11-22 10:11:02'],
        ['id' => 82, 'code' => 'A4JEOXOM', 'nama' => 'Amithya Ratnanggani Sirraduhita', 'lembaga' => 'Ketua DPRD Kota Malang', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/82.png', 'pic' => 'Rizky', 'status' => 'belum', 'created_at' => '2025-11-22 10:12:45', 'updated_at' => '2025-11-22 10:12:45'],
        ['id' => 83, 'code' => 'SRQNIIGE', 'nama' => 'Letkol Inf Dedy Azis', 'lembaga' => 'Komandan Kodim 0833 Kota Malang', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/83.png', 'pic' => 'Adit', 'status' => 'datang', 'created_at' => '2025-11-22 10:18:43', 'updated_at' => '2025-11-27 18:46:17'],
        ['id' => 84, 'code' => 'PEMARR2I', 'nama' => 'H.M Sanusi', 'lembaga' => 'Bupati Malang', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/84.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => '2025-11-22 10:19:27', 'updated_at' => '2025-11-27 19:56:52'],
        ['id' => 85, 'code' => 'NLLCIEBJ', 'nama' => 'Darmadi', 'lembaga' => 'Ketua DPRD Kabupaten Malang', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/85.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => '2025-11-22 10:23:33', 'updated_at' => '2025-11-27 18:53:00'],
        ['id' => 86, 'code' => 'FCQLY83S', 'nama' => 'AKBP Danang Setiyo P.S.', 'lembaga' => 'Kapolres Malang', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/86.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => '2025-11-22 10:24:10', 'updated_at' => '2025-11-27 19:10:07'],
        ['id' => 87, 'code' => 'SFCFBVAX', 'nama' => 'Letkol CZI Bayu Nugroho', 'lembaga' => 'Dandim 0818/Malang-Batu', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/87.png', 'pic' => 'Ainun', 'status' => 'belum', 'created_at' => '2025-11-22 10:24:44', 'updated_at' => '2025-11-22 10:24:44'],
        ['id' => 88, 'code' => '0ELFIHL3', 'nama' => 'Habib Ahmad bin Ustman Alaydrus', 'lembaga' => 'PP Darul Hadits Al Faqihiyah Malang', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/88.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => '2025-11-22 10:28:26', 'updated_at' => '2025-11-27 20:16:56'],
        ['id' => 89, 'code' => 'VSQBXF9Z', 'nama' => 'Prokopim Kota Malang', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/89.png', 'pic' => 'Rizky', 'status' => 'datang', 'created_at' => '2025-11-22 10:28:46', 'updated_at' => '2025-11-27 20:17:20'],
        ['id' => 90, 'code' => 'GBHANFPP', 'nama' => 'Prokopim Kabupaten Malang', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/90.png', 'pic' => 'Siti', 'status' => 'datang', 'created_at' => '2025-11-22 10:29:52', 'updated_at' => '2025-11-27 20:17:46'],
        ['id' => 91, 'code' => 'CUXLSMFA', 'nama' => 'Diskominfo Kota Malang', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/91.png', 'pic' => 'Rizky', 'status' => 'datang', 'created_at' => '2025-11-22 10:38:50', 'updated_at' => '2025-11-27 19:30:52'],
        ['id' => 92, 'code' => 'CKTOO0UW', 'nama' => 'Latar Ijen Resto', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/92.png', 'pic' => 'Siti', 'status' => 'belum', 'created_at' => '2025-11-22 10:39:21', 'updated_at' => '2025-11-22 10:39:21'],
        ['id' => 93, 'code' => 'SOK2RHT1', 'nama' => 'AKBP Andi Yudha Pranata, S.H., S.I.K., M.Si', 'lembaga' => 'Kapolresta Batu', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/93.png', 'pic' => 'Dhani', 'status' => 'belum', 'created_at' => '2025-11-22 11:06:42', 'updated_at' => '2025-11-22 11:06:42'],
        ['id' => 94, 'code' => 'WTSWVCXN', 'nama' => 'H. Muhammad Didik Subiyanto, S.H.', 'lembaga' => 'Ketua DPRD Kota Batu', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/94.png', 'pic' => 'Dhani', 'status' => 'belum', 'created_at' => '2025-11-22 11:07:08', 'updated_at' => '2025-11-22 11:07:08'],
        ['id' => 95, 'code' => 'OMZLW9KT', 'nama' => 'Dinas PUPR Bina Marga Kabupaten Malang', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/95.png', 'pic' => 'Siti', 'status' => 'belum', 'created_at' => '2025-11-22 11:07:27', 'updated_at' => '2025-11-22 11:07:27'],
        ['id' => 96, 'code' => 'IWRSCQ0F', 'nama' => 'Dinas Pendidikan Kabupaten Malang', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/96.png', 'pic' => 'Siti', 'status' => 'belum', 'created_at' => '2025-11-22 11:07:53', 'updated_at' => '2025-11-22 11:07:53'],
        ['id' => 97, 'code' => 'NCCOWHLM', 'nama' => 'Perumda Tirta Kanjuruhan', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/97.png', 'pic' => 'Widodo', 'status' => 'belum', 'created_at' => '2025-11-22 11:08:21', 'updated_at' => '2025-11-22 11:08:21'],
        ['id' => 98, 'code' => 'B9GZHY8Z', 'nama' => 'Grand Palace Hotel', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/98.png', 'pic' => 'Siti', 'status' => 'belum', 'created_at' => '2025-11-22 11:08:57', 'updated_at' => '2025-11-22 11:08:57'],
        ['id' => 99, 'code' => 'WR7ROAW6', 'nama' => 'STAI Ma`had Aly Al-Hikam Malang', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/99.png', 'pic' => 'Siti', 'status' => 'belum', 'created_at' => '2025-11-22 11:09:05', 'updated_at' => '2025-11-22 11:09:21'],
        ['id' => 100, 'code' => 'W6TLHRON', 'nama' => 'Disparbud Kabupaten Malang', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/100.png', 'pic' => 'Siti', 'status' => 'datang', 'created_at' => '2025-11-22 11:09:39', 'updated_at' => '2025-11-27 20:19:01'],
        ['id' => 101, 'code' => 'AYIVM85G', 'nama' => 'Wahid Nurrahman', 'lembaga' => 'Anggota DPRD Kab Probolinggo', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/101.png', 'pic' => 'Ainun', 'status' => 'belum', 'created_at' => '2025-11-22 12:55:57', 'updated_at' => '2025-11-22 12:55:57'],
        ['id' => 102, 'code' => 'S9GHIUKA', 'nama' => 'KH Hamim Kholili', 'lembaga' => 'Ketua PCNU Kabupaten Malang', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/102.png', 'pic' => 'Ainun', 'status' => 'belum', 'created_at' => '2025-11-22 12:56:20', 'updated_at' => '2025-11-22 12:56:20'],
        ['id' => 103, 'code' => '1DMBDDHK', 'nama' => 'Azizah Zamzam', 'lembaga' => 'Ketua Yayasan Duta Pancasila', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/103.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => '2025-11-23 18:23:38', 'updated_at' => '2025-11-27 18:59:10'],
        ['id' => 104, 'code' => 'LKXDLMDQ', 'nama' => 'Zulham Akhmad Mubarrok', 'lembaga' => 'Ketua KNPI Kab Malang', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/104.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => '2025-11-23 18:24:22', 'updated_at' => '2025-11-27 18:59:03'],
        ['id' => 105, 'code' => 'WKFFBC3A', 'nama' => 'Nurochman', 'lembaga' => 'Wali Kota Batu', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/105.png', 'pic' => 'Ainun', 'status' => 'datang', 'created_at' => '2025-11-24 12:39:46', 'updated_at' => '2025-11-27 20:12:40'],
        ['id' => 106, 'code' => 'S2QHHFMW', 'nama' => 'Prof Dr Fadli SH', 'lembaga' => 'FH UB', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/106.png', 'pic' => 'Dhina', 'status' => 'datang', 'created_at' => '2025-11-24 14:19:03', 'updated_at' => '2025-11-27 19:42:47'],
        ['id' => 107, 'code' => 'JN234FRW', 'nama' => 'Prof Fadhilah Putra PhD', 'lembaga' => 'FIA UB', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/107.png', 'pic' => 'Dhina', 'status' => 'belum', 'created_at' => '2025-11-24 14:19:25', 'updated_at' => '2025-11-24 14:19:25'],
        ['id' => 108, 'code' => 'AAAZKNMB', 'nama' => 'Prof Dr Moh Taufiq', 'lembaga' => 'Fisika Um', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/108.png', 'pic' => 'Dhina', 'status' => 'belum', 'created_at' => '2025-11-24 14:19:46', 'updated_at' => '2025-11-24 14:19:46'],
        ['id' => 109, 'code' => 'PL66YIWO', 'nama' => 'Ir H. Hanafi', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/109.png', 'pic' => 'Dhina', 'status' => 'belum', 'created_at' => '2025-11-24 14:20:04', 'updated_at' => '2025-11-24 14:20:04'],
        ['id' => 110, 'code' => 'XMCXGXWV', 'nama' => 'Nurul Kamal MPd', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/110.png', 'pic' => 'Dhina', 'status' => 'datang', 'created_at' => '2025-11-24 14:20:18', 'updated_at' => '2025-11-27 18:19:31'],
        ['id' => 111, 'code' => 'JP68JTVY', 'nama' => 'Dr Widi Atmoko MSi', 'lembaga' => 'Perpustakaan UB', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/111.png', 'pic' => 'Dhina', 'status' => 'belum', 'created_at' => '2025-11-24 14:20:36', 'updated_at' => '2025-11-24 14:20:36'],
        ['id' => 112, 'code' => '90LCWTZH', 'nama' => 'Dahnil Anzar Simanjuntak', 'lembaga' => 'Wakil Menteri Haji dan Umrah R', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/112.png', 'pic' => null, 'status' => 'belum', 'created_at' => '2025-11-24 21:02:14', 'updated_at' => '2025-11-24 21:02:20'],
        ['id' => 113, 'code' => '88QJFNET', 'nama' => 'Iwhan Tri Cahyono', 'lembaga' => 'Kepala Humas PT Gudang Garam Tbk', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/113.png', 'pic' => null, 'status' => 'datang', 'created_at' => '2025-11-24 21:34:55', 'updated_at' => '2025-11-27 19:56:09'],
        ['id' => 114, 'code' => 'AR7UX1RZ', 'nama' => 'Rachmad Mapparawali SEMM', 'lembaga' => 'Direktur BAC', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/114.png', 'pic' => 'CEO', 'status' => 'belum', 'created_at' => '2025-11-25 08:25:04', 'updated_at' => '2025-11-25 08:25:04'],
        ['id' => 115, 'code' => 'GASWO3UJ', 'nama' => 'Sudarmaji', 'lembaga' => 'Redaktur TIMES Indonesia', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/115.png', 'pic' => 'Dhina', 'status' => 'belum', 'created_at' => '2025-11-25 08:56:10', 'updated_at' => '2025-11-25 08:58:42'],
        ['id' => 116, 'code' => '7KAYQGQB', 'nama' => 'H. Abdul Hamid Wahid, M.Ag', 'lembaga' => 'Bupati Bondowoso', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/116.png', 'pic' => null, 'status' => 'datang', 'created_at' => '2025-11-25 15:30:50', 'updated_at' => '2025-11-27 18:08:35'],
        ['id' => 117, 'code' => 'NUBMLH23', 'nama' => 'Dr. H. Najiburrohman, M.Ag., M.Pd', 'lembaga' => 'Rektor Universitas Nurul Jadid', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/117.png', 'pic' => null, 'status' => 'datang', 'created_at' => '2025-11-25 15:31:08', 'updated_at' => '2025-11-27 20:27:47'],
        ['id' => 118, 'code' => 'LQ1YPFNG', 'nama' => 'Kalaksa BPBD Kabupaten Malang', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/118.png', 'pic' => 'Imad', 'status' => 'belum', 'created_at' => '2025-11-25 20:56:22', 'updated_at' => '2025-11-25 20:59:59'],
        ['id' => 119, 'code' => 'CVH7UTSF', 'nama' => 'Kalaksa BPBD Kota Malang', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/119.png', 'pic' => 'Imad', 'status' => 'belum', 'created_at' => '2025-11-25 20:56:36', 'updated_at' => '2025-11-25 21:00:08'],
        ['id' => 120, 'code' => '7EZ5JMZV', 'nama' => 'Kalaksa BPBD Kota Batu', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/120.png', 'pic' => 'Imad', 'status' => 'belum', 'created_at' => '2025-11-25 20:56:47', 'updated_at' => '2025-11-25 21:00:15'],
        ['id' => 121, 'code' => 'CCXPLYFB', 'nama' => 'Doddy Hernanto', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/121.png', 'pic' => 'Wahyu', 'status' => 'belum', 'created_at' => '2025-11-25 20:56:58', 'updated_at' => '2025-11-25 21:00:38'],
        ['id' => 122, 'code' => 'Y65II1FX', 'nama' => 'Febrina', 'lembaga' => 'Kepala Perwakilan BI Malang', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/122.png', 'pic' => null, 'status' => 'datang', 'created_at' => '2025-11-26 08:48:48', 'updated_at' => '2025-11-27 18:48:28'],
        ['id' => 123, 'code' => 'UVPKSQDK', 'nama' => 'Mahdi, SE', 'lembaga' => 'Anggota DPRD Provinsi Jatim', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/123.png', 'pic' => null, 'status' => 'belum', 'created_at' => '2025-11-26 09:02:42', 'updated_at' => '2025-11-26 09:02:42'],
        ['id' => 124, 'code' => '8MYYLZRN', 'nama' => 'Prof. Dr. H. Achmad Supriyanto, M.Pd., M.Si.', 'lembaga' => 'Guru Besar Universitas Negeri Malang.', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/124.png', 'pic' => 'Hainor', 'status' => 'belum', 'created_at' => '2025-11-26 17:30:47', 'updated_at' => '2025-11-26 17:30:47'],
        ['id' => 125, 'code' => 'TJSTO4HC', 'nama' => 'Hj Hasnak Laili', 'lembaga' => 'Ketua IMA Malang', 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/125.png', 'pic' => 'CEO', 'status' => 'datang', 'created_at' => '2025-11-26 21:16:33', 'updated_at' => '2025-11-27 18:37:38'],
        ['id' => 126, 'code' => 'NTBP7E5L', 'nama' => 'JATIM Park', 'lembaga' => null, 'alamat' => null, 'is_register' => null, 'telepon' => null, 'jumlah_orang' => 1, 'qr_code' => 'qrcodes/126.png', 'pic' => null, 'status' => 'datang', 'created_at' => '2025-11-27 10:12:22', 'updated_at' => '2025-11-27 19:48:00'],
    ];
}
